---
# tasks file for chkp-nat-policy
- include_tasks: '{{tasks}}'
  loop_control:
    loop_var: tasks
  loop:
  - objects/package.yml
  - objects/groups.yml
  - objects/networks.yml
  - objects/hosts.yml
  - objects/policy-rules.yml
  - objects/configure-policy-nat-rules.yml
  # - objects/policy-nat-sections.yml