---
# Add or delete host object {{item.name}} in Check Point management server
- name: configure host {{item.name}}
  check_point.mgmt.cp_mgmt_host:
    state: absent
    color: "{{item.color}}"
    name: "{{item.name}}"
    ip_address: "{{item.ip}}"
    nat_settings:
      auto_rule: "{{item.nat_auto_rule}}"
      install_on: "{{item.nat_install_on}}"
      ipv4_address: "{{item.nat_ipv4}}"
      method: "{{item.nat_method}}"
  notify: Publish and install handler
  loop:
  # List of hosts to add
  - { state: present, name: GitLab runner, ip: 192.168.100.53, color: forest green, 
      nat_auto_rule: true, nat_method: static, nat_ipv4: 50.50.50.53, nat_install_on: All
    }

- name: configure host {{item.name}}
  check_point.mgmt.cp_mgmt_host:
    state: present
    color: "{{item.color}}"
    name: "{{item.name}}"
    ip_address: "{{item.ip}}"
  notify: Publish and install handler
  loop:
  # List of hosts to add
  - { state: present, name: search-host-1, ip: 172.123.123.1, color: forest green, }
  - { state: present, name: search-host-2, ip: 172.123.123.2, color: orange, }
