---
# Add or delete security policy package from Check Point management server
- name: Add or delete policy package
  check_point.mgmt.cp_mgmt_package:
    state: present
    access: "{{item.access}}"
    color: "{{item.color}}"
    comments: "{{item.comments}}"
    name: "{{item.name}}"
    threat_prevention: "{{item.threat_prevention}}"
  notify: Publish and install handler
  loop:
  #Policy packages to add
  - { state: present, name: simple_open_policy, comments: Allow all traffic, 
      color: forest green, threat_prevention: true, access: true 
    }