---
# Add access policy rule in Check Point management server
- name: Configure access rule  {{item.position}}
  check_point.mgmt.cp_mgmt_access_rule:
    state: present
    layer: "{{item.layer}}"
    name: "{{item.name}}"
    position: "{{item.position}}"
    source: "{{item.source}}"
    destination: "{{item.destination}}"
    service: "{{item.service}}"
    action: "{{item.action}}"
    track:
      type: "{{item.track_type}}"
    auto_publish_session: True
  loop:
  # List of rules to add
  - { state: present, layer: simple_open_policy Network, name: Rule 1, 
    position: 1, source: search-host-1, destination: ["Any"], service: ["Any"], action: Accept, track_type: log 
    }
  - { state: present, layer: simple_open_policy Network, name: Rule 2, 
    position: 2, source: search-host-2, destination: ["Any"], service: ["Any"], action: Accept, track_type: log 
    }
  # Change Cleanup rule to allow traffic between internal networks
  - { state: present, layer: simple_open_policy Network, name: Cleanup rule, 
    position: 3, source: ["Internal Net", "External Net","Mgmt Net"], destination: ["Internal Net", "External Net","Mgmt Net"], service: ["Any"], action: Accept, track_type: log 
    }
