# ansible-playbook configure-mlm.yml
---
- name: Build inventory
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - role: ../roles/inventory

- name: Task 2.2 - Build an overarching enterprise level policy for deployment to all tenants
  connection: httpapi
  hosts: poc-mds-a
  gather_facts: false
  vars:
    state: present
  roles:
  - role: ../roles/chkp-add-global-policy