# ansible-playbook configure-mlm.yml
---
- name: Build inventory
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - role: ../roles/inventory

- name: Playbook for rules and objects exported to Ansible from the Check Point API
  connection: httpapi
  hosts: poc-mds-a
  gather_facts: false
  vars:
    state: present
  roles:
  - role: ../roles/chkp-add-demo-mode-policy