# ansible-playbook configure-mlm.yml
---
- name: Build inventory
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - role: ../roles/inventory

- name:  Build domain log server for domain a
  hosts: poc-mds-a
  connection: httpapi
  gather_facts: false
  roles:
  - role: ../roles/chkp-add-log-export