# ansible-playbook configure-mlm.yml
---
- name: Build inventory
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - role: ../roles/inventory

- name:  add package
  hosts: poc-mds-a
  connection: httpapi
  gather_facts: false
  vars:
    state: present
  roles:
  - role: ../roles/chkp-central-deployment-add-package

- name:  Upgrade Check Point cluster
  hosts: domain-a
  connection: httpapi
  gather_facts: false
  vars:
    state: present
  roles:
  - role: ../roles/chkp-central-deployment-install-package