- name: Add, set or delete mail server
  check_point.mgmt.cp_mgmt_host:
    state: '{{state}}'
    name: AWS Mail server
    ip_address: 192.172.151.12
    color: blue
    comments: my mail server host objects

- name: Add, set or delete web server
  check_point.mgmt.cp_mgmt_host:
    state: '{{state}}'
    name: AWS Web server
    ip_address: 10.123.214.55
    color: yellow
    comments: my blue jump host object