#- debug:
#    msg: '{{ansible_checkpoint_domain}}'

- name: Configure  global assignment for domains
  cp_mgmt_global_assignment:
    dependent_domain: '{{item.domain}}'
    global_access_policy: '{{item.global_access_policy}}'
    global_domain: Global
    global_threat_prevention_policy: ''
    manage_protection_actions: false
    state: '{{item.state}}'
  loop:
  # List of domains and global policy to assign
  - { state: present, domain: domain-a, global_access_policy: overarching_ent_lvl_pol }
  - { state: present, domain: domain-b, global_access_policy: overarching_ent_lvl_pol }

- name: Publish Current Changes
  check_point.mgmt.cp_mgmt_publish:

- name: Assign the global-assignment
  cp_mgmt_assign_global_assignment:
    dependent_domains: 
    - domain-a
    - domain-b
    global_domains: Global