---
# Add or delete host object {{item.name}} in Check Point management server
- name: add-host or delete-host
  check_point.mgmt.cp_mgmt_host:
    state: "{{state}}"
    color: "{{item.color}}"
    name: "{{item.name}}"
    ip_address: "{{item.ip}}"
#    nat_settings:
#      auto_rule: "{{item.nat_auto_rule}}"
#      install_on: "{{item.nat_install_on}}"
#      ipv4_address: "{{item.nat_ipv4}}"
#      method: "{{item.nat_method}}"
  notify: Publish and install handler
  loop:
  # List of hosts to add
  - { state: present, name: g-exchange-mail, ip: 50.50.55.10, color: pink, 
      nat_auto_rule: true, nat_method: static, nat_ipv4: 172.27.254.210, nat_install_on: All
    }