---
- name: Add domain level permission profile
  check_point.mgmt.cp_mgmt_domain_permissions_profile:
    state: '{{item.state}}'
    name: '{{item.name}}'
    permission_type: '{{item.permission_type}}'
    access_control:
      show_policy: '{{item.ac_show_policy | default(omit)}}'
      policy_layers:
        edit_layers: '{{item.ac_policy_layers | default(omit)}}'
    threat_prevention:
      policy_layers: '{{item.tp_policy_layers | default(omit)}}'
      edit_layers: '{{item.tp_edit_layers | default(omit)}}'
      edit_settings: '{{item.tp_edit_settings | default(omit)}}'
      policy_exceptions: '{{item.tp_policy_exceptions | default(omit)}}'
      profiles: '{{item.tp_profiles | default(omit)}}'
      protections: '{{item.tp_protections | default(omit)}}'
      install_policy: '{{item.tp_install_policy | default(omit)}}'
      ips_update: '{{item.tp_ips_update| default(omit)}}'
    others:
      https_inspection: '{{item.ot_https_inspection | default(omit)}}'
    comments: '{{item.comments}}'
    color: '{{item.color}}'
  register: permission_profile
  notify: Publish handler
  loop:
  # List of domains and global policy to assign
  - { state: present, name: Web Layer manager, permission_type: customized, 
      ac_show_policy: true, ac_policy_layers: By Selected Profile In A Layer Editor,
      tp_policy_layers: disabled, tp_edit_settings: false, tp_policy_exceptions: disabled, tp_profiles: disabled,
      tp_protections: disabled, tp_install_policy: false, tp_ips_update: false,
      ot_https_inspection: disabled,
      comments: Restrict admin to make changes in Web control layer, color: blue,  
    }
  - { state: present, name: Guest Layer manager, permission_type: customized, 
      ac_show_policy: true, ac_policy_layers: By Selected Profile In A Layer Editor, 
      tp_policy_layers: disabled, tp_edit_settings: false, tp_policy_exceptions: disabled, tp_profiles: disabled,
      tp_protections: disabled, tp_install_policy: false, tp_ips_update: false,
      ot_https_inspection: disabled,
      comments: Restrict admin to make changes in Guest exception layer, color: sea green, 
    }

- set_fact: 
    web_permission_profile_uid: "{{permission_profile.results[0]['add-domain-permissions-profile'].uid}}"
    guest_permission_profile_uid: "{{permission_profile.results[1]['add-domain-permissions-profile'].uid}}"
  when: permission_profile.results[0]['add-domain-permissions-profile'].uid is defined or permission_profile.results[1]['add-domain-permissions-profile'].uid is defined

- set_fact: 
    web_permission_profile_uid: "{{permission_profile.results[0]['set-domain-permissions-profile'].uid}}"
    guest_permission_profile_uid: "{{permission_profile.results[1]['set-domain-permissions-profile'].uid}}"
  when: permission_profile.results[0]['set-domain-permissions-profile'].uid is defined or permission_profile.results[1]['set-domain-permissions-profile'].uid is defined