- name: set-access-section on top of GW Access in Shared_Policy Network
  check_point.mgmt.cp_mgmt_access_section:
    layer: Shared_Policy Network
    name: GW Access
    position: 1
    state: '{{state}}'
    auto_publish_session: true
- name: set-access-section on top of Guest rules in Shared_Policy Network
  check_point.mgmt.cp_mgmt_access_section:
    layer: Shared_Policy Network
    name: Guest Access Grant
    position: 4
    state: '{{state}}'
    auto_publish_session: true

- name: set-access-section on top of Cleanup in Shared_Policy Network
  check_point.mgmt.cp_mgmt_access_section:
    layer: Shared_Policy Network
    name: Cleanup
    position: 5
    state: '{{state}}'
    auto_publish_session: true
