---
# tasks file for chkp_add_mds_mdls
- name: Create MDS & MDLS if it does not exist
  include_tasks: mgmt_api_add-mds.yml
- name: Allow any client to connect to the domains
  include_tasks: set-trusted-client.yml
